language: python
python:
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scottydelta
  password:
    secure: YmDMEeTCF2pI/4wcw0sm7kVadKYx85loRzFfNOQ9TBpowBYUQqAM0ZbcAEeR3H4rVDjkLZR69gZZQOtOOX6vzfNv+kHYGmWnfSKlpy8pVSkVLuarS8/biU8qNFGYbt2VjVW/Vwc9uz4hR2bZrlnjf4RYyVfYr+6viMHx7G1XiyXLGN1HRhsd+ZvRs9s8B+ByO/FPC6gjG/wr3dG9I916kXRRz+eJFPYjUHzz7h3gxKnzgN147UWLBBjTAOg7j9HezCLS0DH/Dx6YgTH8Fq/g8pIHaAmvgjwMEJJfSiWGrDADZhNPZiTtEM8few0mMmKU0vys0qePleB20Ll/ItKhK875l9BwsrAqlgUu9A8jK6YnSWAFIYsHi4yBOZ94DmmGPGFMJdQv5TtGuw9XjhUUz1cj6ljhF80x1t22JQqU1DluNamEwJfEoAbQ5tswS2ghkFbe01VAe+U/sGY4dgmAALH+FUpQbd7UOSatHYMKfqXvuawOS4oAf9xuafrySoH876WyAl13sTtmTiIrsOkJlE8ZhixRFlHX281c/917COapBsP56Ej6oKEEv2PXBfDmr92g6EGtrDj8rA/uosdH5z9TR0BZBtIzXSzS0YJqHa2Fn1EDP0MrfQRSsLi1GkmtGle9nfJ8jUOVRbHJkirbvfbB41rsXYz5yAR3xuuAFLE=
  on:
    tags: true
    repo: scottydelta/esq
    python: 3.8
