name: build

on:
    push:
        branches:
            - develop

permissions:
    contents: read

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - uses: ammaraskar/sphinx-action@master
          with:
              pre-build-command: python -m pip install -r requirements_dev.txt
              docs-folder: "docs/"
              
    build:
        runs-on: ubuntu-latest


        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.x"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build
            - name: Build package
              run: python -m build
